name: iota-netatmo
version: '0.2'
summary: Read data from NetAtmo sensor and write it to the IOTA Tangle.
description: |
  POC script to read sensor data from the public NetAtmo API and attach it to
  the IOTA Tangle.

grade: devel
confinement: strict

parts:
  iota-netatmo:
    build-packages:
      - libssl-dev
      - libffi-dev
    source: https://github.com/ivoscc/iota-sensor-poc.git
    plugin: python
    python-version: python3
  mam:
    source: https://github.com/ivoscc/mam.client.js.git
    node-engine: 7.10.0
    node-packages:
     - commander
     - crypto.iota.js
     - iota.lib.js
    plugin: nodejs
    filesets:
        files:
           - -LICENSE
    stage:
        - $files
    prime:
        - $files

apps:
  iota-netatmo:
    command: iota-sensor
    plugs: [network, home]
  mam:
    command: mam_encrypt
